# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    labels:
      - dependencies
    cooldown:
      default-days: 10

  # Composer: Tooling
  - package-ecosystem: composer
    directories:
      - "/changelog"
      - "/collaboration-checker"
      - "/label-updater"
      - "/milestonemover"
      - "/milestoneupdater"
      - "/sensitive-issue-searcher"
      - "/spdx-convertor"
    versioning-strategy: "increase"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Berlin
    labels:
      - dependencies
    cooldown:
      default-days: 10
