# This workflow is monitoring the time-to-wait for 
name: Github action monitoring

on:
  workflow_dispatch:
  schedule:
    - cron: '7/15 * * * *'

jobs:
  monitoring:
    runs-on: ubuntu-latest
    container:
      image: debian

    steps:
      - name: Ping
        run: echo 'ping'
